# fly.toml app configuration file generated for rss-feed on 2023-07-08T17:34:35+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rss-feed"
primary_region = "arn"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
