spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/postgres
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_OAUTH_CLIENT_ID}
            client-secret: ${GITHUB_OAUTH_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            client-name: GitHub
            authorization-grant-type: authorization_code
            provider:
              user-info-uri: https://api.github.com/user
            user-name-attribute: id
