spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/postgres
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_OAUTH_CLIENT_ID}
            client-secret: ${GITHUB_OAUTH_CLIENT_SECRET}
            redirect-uri: "https://rss-feed.fly.dev/login/oauth2/code/github"
