name: Deploy to Fly.io Workflow
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21
          cache: 'gradle'
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Build JAR
        run: ./gradlew bootJar
      - name: Deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Check deploy
        run: |
          response=$(curl -s -o /dev/null -m 60 -w "%{http_code}" https://rss-feed.fly.dev/actuator/health)
          if [ $response -eq 200 ]; then
            echo "Application is healthy"
          else
            echo "Deploy failed"
            exit 1
          fi

