name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: 24
          cache: 'gradle'

      - name: Build
        run: ./gradlew build -x test

      - name: Run tests
        run: ./gradlew test
