name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'
      - name: Run JUnit tests
        run: ./gradlew build
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3.7.2
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
