name: Trigger post service
on:
  schedule:
    - cron: '0 */20 * * *'
jobs:
  make-request:
    runs-on: ubuntu-latest
    steps:
      - name: Login to get token
        id: login
        run: |
          login_response=$(curl -s -X POST https://rss-feed.fly.dev/api/auth/login \
            -H "Content-Type: application/json" \
            -d '{"username": "${{ secrets.API_USERNAME }}", "password": "${{ secrets.API_PASSWORD }}"}')
          token=$(echo $login_response | jq -r '.token')
          echo "::add-mask::$token"
          echo "TOKEN=$token" >> $GITHUB_OUTPUT

      - name: Request health check
        run: |
          health_response=$(curl -s https://rss-feed.fly.dev/actuator/health)
          echo "Health response: $health_response"

      - name: Wait for 30 seconds
        run: sleep 30s

      - name: Delete read posts older than 30 days
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ steps.login.outputs.TOKEN }}" -X POST https://rss-feed.fly.dev/api/posts/cleanup)
          echo "Response from API: $response"

      - name: Trigger post service
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ steps.login.outputs.TOKEN }}" -X POST https://rss-feed.fly.dev/api/posts/fetch-latest)
          echo "Response from API: $response"
