name: Trigger post service
on:
  schedule:
    - cron: '0 */20 * * *'
jobs:
  make-request:
    runs-on: ubuntu-latest
    steps:
      - name: Request health check
        run: |
          health_response=$(curl -H "X-API-Token: ${{ secrets.API_TOKEN }}" https://rss-feed.fly.dev/actuator/health)
          echo "Health response: $health_response"

      - name: Wait for 30 seconds
        run: sleep 30s

      - name: Delete read posts older than 30 days
        run: |
          response=$(curl -H "X-API-Token: ${{ secrets.API_TOKEN }}" -X POST https://rss-feed.fly.dev/api/posts/cleanup)
          echo "Response from API: $response"

      - name: Trigger post service
        run: |
          response=$(curl -H "X-API-Token: ${{ secrets.API_TOKEN }}" -X POST https://rss-feed.fly.dev/api/posts/fetch-latest)
          echo "Response from API: $response"
